name: linting

on:
  pull_request:
    branches: 
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install modules
        run: npm ci
        
      - name: ESLint Plus
        uses: bradennapier/eslint-plus-action@v3
        with:
          extensions: .ts,.tsx


