name: linting

on:
  pull_request:
    branches: 
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: npm install
      
    - name: Run ESLint
      run: eslint . --ext .ts,.tsx
