name: linting

on:
  pull_request:
    branches: 
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Eslint Reviewdog 
        uses: reviewdog/action-eslint@v1.16.1
        with:
          reporter: github-pr-review 
