name: node-build

on:
  push: 
    branch:
      master


jobs: 
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Build using Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build --if-present
      - name: Generate Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
      - run: npm version patch --no-git-tag-version
      - name: Publish package
        run: npm publish --access public 
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}